title: mattrighetti
description: Just another programming blog
baseurl: ""
url: "https://mattrighetti.com"
github_username:  mattrighetti

author: Mattia Righetti

host: 0.0.0.0

collections:
  positions:
    order:
      - amazon-sde-intern.adoc
      - fullstack-engineer-polimi.adoc
  projects:
    order:
      - ulry.adoc
      - libgen-telegram-bot.adoc
      - hn-reader-macos.adoc
      - chmod-util.adoc
      - group-activity-telegram-bot.adoc
      - lode.adoc

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed

highlighter: rouge

asciidoctor:
  attributes:
    - icons=font
