title: mattrighetti
description: Just another programming blog
baseurl: ""
url: "https://mattrighetti.com"
github_username: mattrighetti

author: Mattia Righetti

host: 0.0.0.0

collections:
  positions:
    order:
      - cloudflare-systems-engineer.adoc
      - tor-core-dev.adoc
      - anthropos-fullstack-engineer.adoc
      - amazon-sde-intern.adoc
      - fullstack-engineer-polimi.adoc
  contributions:
    order:
      - tor-project-gsoc2023.adoc
  projects:
    order:
      - hn-widgets.adoc
      - envelope.adoc
      - network-status-api.adoc
      - ulry.adoc
      - libgen-telegram-bot.adoc
      - hn-reader-macos.adoc
      - chmod-util.adoc
      - group-activity-telegram-bot.adoc
      - lode.adoc
  threads:
    output: true
    permalink: /threads/:path/

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from

asciidoctor:
  attributes:
    - icons=font
