title: mattrighetti
description: >
  Just another programming blog
baseurl: ""
url: "https://mattrighetti.github.io"
github_username:  mattrighetti

author: Mattia Righetti

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed

highlighter: rouge

asciidoctor:
  attributes:
    - icons=font