= Resume
:layout: default
:exclude: false

Welcome to my resume! Also available in
https://mattrighetti.github.io/resume.pdf[.pdf]

=== Personal Details

[horizontal]
Name:: Mattia Righetti
Contacts::
- icon:github[] https://github.com/mattrighetti
- icon:link[] http://mattrighetti.github.io
- icon:envelope[] See GitHub profile

=== Education
- 2019-2022, MSc in Computer Science, _Politecnico di Milano_
- 2015-2019, BSc in Computer Science, _Politecnico di Milano_

=== Professional Experience

==== SDE Intern, Amazon
icon:calendar[title="Period"] Jun 2022 - Current
- Developed and optimized new backend APIs that impacted many different teams and automated most of the interactions that other teams had with our service, making it faster, more efficient, much more available and paved the way for new features and ideas sparkled from wider access to the service
- Developed a web application interface using Go and server-side rendering to showcase our backend API to other teams and which also turned out to be extremely valuable to onboard people on our APIs
- Deployed and maintained OSRM service on AWS EC2 instance that freed the team from other internal API limitations and also enabled a finer grained control of crucial parameters that improved the value delivered to our customers
- Data pipelines management and data manipulation with Apache Airflow, AWS Glue and AWS ECR. Improved parallelisms of data transformation pipelines making them a lot more faster, cheaper and increased overall throughput of data
- Setup multiple pipeline to manage CI/CD of services with the use of AWS CDK and AWS CloudFormation

==== Department of Civil and Environmental Engineering 
icon:calendar[title="Period"] Jun 2018 to Sep 2021 +
icon:link[] https://www.dica.polimi.it/?lang=en
- Designed and maintained MySQL database, implemented scheduled jobs to periodically backup data and upload it to dedicated S3 bucket
- Developed webapp frontend with HTML and CSS, later moved to Vue
- Developed backend REST APIs with Go and Node.js to feed models data to the frontend webapp
- Setup NGINX daemon to serve frontend content and route APIs requests to internal Docker network
- VPS administration and maintenance including domain registration and networking setup

=== Publications

==== Model-Driven Development of Distributed Ledger Applications
icon:users[title="Authors"] Piero Fraternali, S. L. Herrera Gonzalez, Matteo Frigerio, Mattia Righetti +
icon:link[] coming soon

=== Skills
- Python, Bash, Java, Rust, Go, Swift
- PostreSQL, MySQL, Docker, NGINX
- AWS EC2, AWS S3, AWS Lambda
