name: Build and deploy

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/cache@v3
      with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - run: bundle install && bundle exec jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _site
        force_orphan: true
    
    - name: Check changed files
      run: |
        git diff --name-only HEAD HEAD~1 | \
        grep _posts | \
        sed 's/_posts\///' | sed 's/\.adoc//' | \
        awk -F '-' '{ printf("https://mattrighetti.com/%s/%s/%s/%s.html\n", $1, $2, $3, substr($0,12)) }' | \
        jq -Rn '["https://mattrighetti.com/", inputs]'

    - name: Purge CF Cache
      run: |
        sleep 60
        git diff --name-only HEAD HEAD~1 | \
        grep _posts | \
        sed 's/_posts\///' | sed 's/\.adoc//' | \
        awk -F '-' '{ printf("https://mattrighetti.com/%s/%s/%s/%s.html\n", $1, $2, $3, substr($0,12)) }' | \
        jq -Rn '{"files": ["https://mattrighetti.com/", inputs]}' | \
        curl -s -X POST \
          --url https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ secrets.CF_API_TOKEN }}' \
          --data-binary @- | \
        jq